server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  profiles:
    active: dev
  datasource:
    druid:
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 10000
      filters: stat,wall,slf4jre
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: root
        login-password: tsnew
        allow:
        deny:
  thymeleaf:
    cache: false
    mode: HTML
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  aop:
    proxy-target-class: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.puboot.model

